"""Correção de erro de digitação na tabela Materia e pequena mudanca de caracteres na tabela Arquivo.

Revision ID: 378ded59ec0a
Revises: 4444f0261a00
Create Date: 2026-10-07 23:16:40.285156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '378ded59ec0a'
down_revision = '4444f0261a00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('arquivos', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_nullable=False)

    with op.batch_alter_table('materias', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_materia_curso', ['nome', 'id_curso'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materias', schema=None) as batch_op:
        batch_op.drop_constraint('uq_materia_curso', type_='unique')

    with op.batch_alter_table('arquivos', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
