"""Adicionando a tabela cargo para professores.

Revision ID: 47a34cbea1ad
Revises: 378ded59ec0a
Create Date: 2026-10-10 15:01:50.573266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47a34cbea1ad'
down_revision = '378ded59ec0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cargos',
    sa.Column('id_cargo', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_cargo', name='pk_cargos'),
    sa.UniqueConstraint('nome', name='uq_cargos_nome')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_cargo', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('especializacao', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('lattes_url', sa.String(length=255), nullable=True))
        # 1. FOI ADICIONADO O NOME DA CONSTRAINT AQUI:
        batch_op.create_foreign_key('fk_usuarios_id_cargo_cargos', 'cargos', ['id_cargo'], ['id_cargo'])
        

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        # 2. SUBSTITUÍDO 'None' PELO NOME ESCOLHIDO PARA EVITAR O ERRO:
        batch_op.drop_constraint('fk_usuarios_id_cargo_cargos', type_='foreignkey')
        batch_op.drop_column('lattes_url')
        batch_op.drop_column('especializacao')
        batch_op.drop_column('id_cargo')

    op.drop_table('cargos')
    # ### end Alembic commands ###
