"""Alterando unicidade das matérias por curso.

Revision ID: 4ea202e11d28
Revises: 5aadddf94b1c
Create Date: 2026-09-23 22:04:39.307976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ea202e11d28'
down_revision = '5aadddf94b1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materias', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('materias_nome_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materias', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('materias_nome_key'), ['nome'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
