"""Estrutura inicial.

Revision ID: 5aadddf94b1c
Revises: 
Create Date: 2026-09-22 16:00:34.748279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aadddf94b1c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes_tag',
    sa.Column('id_classe', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=20), nullable=False),
    sa.Column('cor', sa.Enum('AZUL', 'AMARELO', 'VERDE', 'ROSA', 'ROXO', name='cortag'), nullable=False),
    sa.PrimaryKeyConstraint('id_classe'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('cursos',
    sa.Column('id_curso', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_curso'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nome_completo', sa.String(length=50), nullable=False),
    sa.Column('nome_usuario', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=True),
    sa.Column('foto_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nome_usuario')
    )
    op.create_table('materias',
    sa.Column('id_materia', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('id_curso', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_curso'], ['cursos.id_curso'], ),
    sa.PrimaryKeyConstraint('id_materia'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('tags',
    sa.Column('id_tag', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=20), nullable=False),
    sa.Column('id_classe', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_classe'], ['classes_tag.id_classe'], ),
    sa.PrimaryKeyConstraint('id_tag'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('conteudos',
    sa.Column('id_conteudo', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('id_materia', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_materia'], ['materias.id_materia'], ),
    sa.PrimaryKeyConstraint('id_conteudo'),
    sa.UniqueConstraint('nome', 'id_materia', name='uq_conteudo_materia')
    )
    op.create_table('materiais',
    sa.Column('id_material', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=50), nullable=False),
    sa.Column('subtitulo', sa.String(length=100), nullable=True),
    sa.Column('descricao', sa.String(length=300), nullable=False),
    sa.Column('conteudo_textual', sa.Text(), nullable=True),
    sa.Column('data_publicacao', sa.DateTime(timezone=True), nullable=False),
    sa.Column('visualizacoes', sa.Integer(), nullable=False),
    sa.Column('downloads', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_curso', sa.Integer(), nullable=False),
    sa.Column('id_materia', sa.Integer(), nullable=False),
    sa.Column('id_conteudo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_conteudo'], ['conteudos.id_conteudo'], ),
    sa.ForeignKeyConstraint(['id_curso'], ['cursos.id_curso'], ),
    sa.ForeignKeyConstraint(['id_materia'], ['materias.id_materia'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_material')
    )
    op.create_table('arquivos',
    sa.Column('id_arquivo', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('nome_unico', sa.String(length=300), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('tamanho', sa.Integer(), nullable=False),
    sa.Column('arquivo_url', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=255), nullable=False),
    sa.Column('data_upload', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id_material', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_material'], ['materiais.id_material'], ),
    sa.PrimaryKeyConstraint('id_arquivo')
    )
    op.create_table('favoritos',
    sa.Column('id_favorito', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_material', sa.Integer(), nullable=False),
    sa.Column('data_favoritado', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_material'], ['materiais.id_material'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_favorito'),
    sa.UniqueConstraint('id_usuario', 'id_material', name='uq_usuario_material')
    )
    op.create_table('material_tag',
    sa.Column('id_material', sa.Integer(), nullable=False),
    sa.Column('id_tag', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_material'], ['materiais.id_material'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_tag'], ['tags.id_tag'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_material', 'id_tag')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('material_tag')
    op.drop_table('favoritos')
    op.drop_table('arquivos')
    op.drop_table('materiais')
    op.drop_table('conteudos')
    op.drop_table('tags')
    op.drop_table('materias')
    op.drop_table('usuarios')
    op.drop_table('cursos')
    op.drop_table('classes_tag')
    # ### end Alembic commands ###
