"""Pequeno ajuste na tabela classe_tag.

Revision ID: 97961184d356
Revises: 4ea202e11d28
Create Date: 2026-09-28 14:20:26.448793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97961184d356'
down_revision = '4ea202e11d28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes_tag', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes_tag', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
